language: cpp
script: cmake
compiler: gcc 

before_install:
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libfftw3-dev libboost1.55-dev libboost-filesystem1.55-dev libboost-test1.55-dev libboost-random1.55-dev libhdf5-serial-dev
  - sudo pip install cpp-coveralls --use-mirrors

before_script:
  - mkdir build
  - cd build
  - cmake ..
  
script: make && make test

env:
  - CTEST_OUTPUT_ON_FAILURE=""

after_success:
  - coveralls --exclude test
